# Generated by Django 5.1.1 on 2024-10-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolist',
            new_name='TodolistItem',
        ),
    ]
